[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "bottle-nameko"
version = "0.1.0"
readme = "README.md"
description = "Nameko RPC integration for Bottle applications"

requires-python = ">=3.10,<3.11"

dependencies = [
    "bottle>=0.13,<0.14",
    "nameko==2.14.1",
    "eventlet==0.40.3",
    "setuptools>=77,<81",
]

[project.optional-dependencies]
dev = ["pytest", "WebTest"]

[tool.setuptools.packages.find]
include = ["bottle_nameko*"]

[project.scripts]
bottle-nameko = "bottle_nameko.cli:main"